version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo "Installing dependencies..."
      - npm install  # Installs dependencies defined in package.json

  build:
    commands:
      - echo "No build step required, skipping build phase"

  post_build:
    commands:
      - echo "Build complete"
      - echo "Application is ready to deploy"

artifacts:
  files:
    - server.js
    - package.json
    - package-lock.json
    - node_modules/**/*
